[package]
name = "serve"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "serve"
path = "main.rs"

[dependencies]
anyhow = "1.0"
tiny_http = "0.12"
